### ISSUE TITLE
save_pdf() doesn't include images from Markdown files

### ISSUE THREAD

**Issue by espenol** [domvwt/esparto#60]
* esparto version: 2.0.0
* Python version: 3.8
* Operating System: Debian Bullseye, WSL

### Description

I'm using your library to generate some very simple pdf documentation using existing markdown files. Some of these markdown files have included images, the images are properly displayed when I do `page.save_html()`, but when I do `page.save_pdf()` only the image description (and not the image itself) is included 

I expected the pdf output to include the images just as the html output does.

**Comment by domvwt** [comment]
Hi @espenol ,

Thanks for raising this issue. I've tried replicating the problem but my PDF is rendering correctly with the image. Could you try running this code on your system?

```python
import esparto as es

image_url = "https://unsplash.com/photos/phIFdC6lA4E/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8Mnx8bW91bnRhaW58fDB8fHx8MTY0MzM1NTM4OQ&force=true&w=640"

my_markdown = f"""
# This is the Title

Here is the body

![my image]({image_url})

"""

page = es.Page()
page += es.Markdown(my_markdown)
page.save_pdf("my-pdf.pdf")
```

The pdf should look like this:

![image](https://user-images.githubusercontent.com/25273440/151534586-1b141956-3bd2-4a2f-97b5-dbd554e02cae.png)

If this code works for you then it could be an issue with the image link.  If you can share an example I'll take a look.

Thanks

**Comment by espenol** [comment]
Hey! The images are not online so there are no urls, I use relative paths instead (markdown in a closed github repo). I'll try to make an example over the weekend, if this is something that's supposed to be supported?
